<div class="headerinfomenu">
<ul>
<li><div class="cod-icon"><a class="cashondelivery-cls" href=""></a></div>
<div class="codInfo_popups"><span class="top_dropdown_heading">Cash On Delivery</span><br><p>We provide cash on delivery to most parts of India. So don't stress if you don't have a credit card or don't want to use it. Just pick the COD option!</p></div>
</li>
<li><div class="shipping-icon"><a class="freeshipping-cls" href="#"></a></div>
<div class="shippingInfo_popups"><span class="top_dropdown_heading">Free Shipping</span><br><p>Free Shipping on all orders over Rs. 2000. Click here for our shipping policy.</p></div>
</li>
<li><div class="contct-icon"><a class="contact-us-cls" href="#"></a></div>
<div class="contctInfo_popups"><span class="top_dropdown_heading">Contact Us</span><br><p>Phone - +011-39595319 <br>Monday to Saturday<br><a href="#">Email - woof@headsupfortails.com</a></p></div>
</li>
<li><div class="whtsap-icon"><a class="whatsapp-cls" href="#"></a></div>
<div class="whtsapInfo_popups"><span class="top_dropdown_heading">Opening Timings</span><br><p>Monday to Saturday <br>10 AM - 6 PM<br>Phone : +919717175707</p></div>
</li>
</ul>



	
</div>