<div class="top-help-cls">
	<a href="#">
		<span class="hidden-tablet">help</span>
	</a>
	<div class="cw-drop cw-drop-help">
		<div class="cw-help-top">
		<div class="expert-247">
			<p>
				Get help from our experts 24/7
				<span>011-39595319</span>
			</p>
			</div>
			<div class="cw-help-mid">
			<span class="lp-chat-container"><a class="livechat" data-lp-event="click">Chat Live</a></span>
			<a class="emailus" href="/app/content/contact">Contact Us</a>
		</div>
		<div class="cw-help-bottom">
			<span><a href="#">Track Order -</a></span>
			<span><a href="#">Returns -</a></span>
			<span><a href="#">Shipping Info </a></span>
		</div>
		</div>
		
	</div>
</div>

<div class="myaccount-link"><ul class="account-listNew">

<li><a href="#"><?php echo __('My account') ?></a>
<ul class="wishlist-menu">
<li><a href="<?php echo $this->getUrl('customer/account/create'); ?>"><?php echo __('My Account') ?></a>
<li><a href="<?php echo $this->getUrl('wishlist'); ?>"><?php echo __('My Wishlist') ?></a></li>
<li><a href="<?php echo $this->getUrl('checkout/cart/'); ?>"><?php echo __('My Cart') ?></a></li>
<li><a href="<?php echo $this->getUrl('checkout'); ?>"><?php echo __('Checkout') ?></a></li>
</ul>
</li>
</ul></div>


