<?php $objectManager= \Magento\Framework\App\ObjectManager::getInstance();
		$storeManager=$objectManager->create('\Magento\Store\Model\StoreManagerInterface');
		$baseURL_l = $storeManager->getStore()->getBaseUrl();?>
<span type="cancel" class="cancel" id="cancelpopup">X</span>
<form id="faq-form" name="faq-form" action="#" method="post" enctype="multipart/form-data" onsubmit="return(validateForm());>
		<span id="successmsg">&nbsp;</span>
	<div class="rendered-form">
		<div class="form-group field-name">
			<label for="name" class="fb-text-label">Name<span class="fb-required">*</span></label>
			<input type="text" placeholder="enter your name" class="form-control" name="name" id="name" required="required" aria-required="true">
		</div>
		<div class="form-group field-email">
			<label for="mail" class="fb-text-label">E-mail<span class="fb-required">*</span></label>
			<input type="email" placeholder="enter your Email"id="mail" name="email" class="form-control" required="required" aria-required="true"/>
		</div>
		<div class="form-group field-mobile">
			<label for="mobile" class="fb-text-label">Phone Number<span class="fb-required">*</span></label>
			<input type="text" placeholder="Enter your Phone Number" class="form-control" name="phone" maxlength="10" id="phone" required="required" aria-required="true">
		</div>
		<div class="form-group field-applied">
			<label for="applied" class="fb-text-label">Order Id</label>
			<input type="text" class="form-control" name="orderId" id="orderId" required="required" aria-required="true">
		</div>
		<div class="form-group field-intro">
			<label for="intro" class="fb-textarea-label">Subject</label>
			<select id="chat_dropdown" name="subjectTitle">
				<option selected="" value="-1">Select an Option</option>
				<option value="I want to place an Order">I want to place an Order</option>
				<option value="Order Related">Order Related</option>
				<option value="Payment related">Payment related</option>
				<option value="Complaint">Complaint</option>
				<option value="Others">Others</option>
			</select>
		</div>
		<div class="form-group field-description">
			<label for="intro" class="fb-textarea-label">Description</label>
			<textarea type="textarea" class="form-control" name="description" rows="5" id="description"></textarea>
		</div>
		<div class="form-group field-apply">
			<?php /* ?><button type="button" class="btn btn-success" name="submit" id="apply-success">Button</button><?php */ ?>
			<input type="button" class="btn btn-success" value="submit comment" id="submit-query"/>
		</div>
		<span id="formLoader">&nbsp;</span>
	</div>
</form>
<script>
//========================Comment Form======================================//
require(['jquery'], function() {
	jQuery(document).ready(function() {		
	jQuery( "#submit-query" ).click(function(event) {
		 event.preventDefault();
		 // validation start=============
		 
	var x = document.forms["faq-form"]["name"].value;
    var x1 = document.forms["faq-form"]["phone"].value;
    var x3 = document.forms["faq-form"]["email"].value;
   // var x5 = document.forms["faq-form"]["orderId"].value;
    var x6 = document.forms["faq-form"]["description"].value;

	if( x == "" ){
		 alert( "Please provide your Name!" );
		 document.forms["faq-form"]["name"].focus() ;
		 return false;
	}if( x3 == "" ){
		 alert( "Please provide your Email!" );
		 document.forms["faq-form"]["email"].focus() ;
		 return false;
	}else if(x3){
		var atpos = x3.indexOf("@");
		var dotpos = x3.lastIndexOf(".");
		if (atpos<1 || dotpos<atpos+2 || dotpos+2>=x3.length) {
			alert("Not a valid e-mail address");
			document.forms["faq-form"]["email"].focus() ;
			return false;
    }
	}
	if( x1 == "" ){
		 alert( "Please provide your Phone!" );
		 document.forms["faq-form"]["phone"].focus() ;
		 return false;
	}else if((isNaN(x1)) || (x1.length < 10)){
		alert("Please enter valid Phone");
		document.forms["faq-form"]["phone"].focus() ;
        return false;
	}
	/* if( x5 == "" ){
		 alert( "Please provide your orderId!" );
		 document.forms["faq-form"]["orderId"].focus() ;
		 return false;
	} */
	if( x6 == "" ){
		 alert( "Please provide the description!" );
		 document.forms["faq-form"]["description"].focus() ;
		 return false;
	}
		 
		 //=================================
		if(1){
			//var form = jQuery('#career-form')[0];
		var data = jQuery('#faq-form').serialize();
			jQuery.ajax({
				url:"<?php echo $this->getUrl().'faqquery/index/query';?>",
				type:'POST',
				data: data,
				beforeSend:function()
				{
					 jQuery("#formLoader").html("<img src='http://119.82.68.254/headsupfourtails/pub/media/zipcode/loading.gif'/>");
					 jQuery("#formLoader").show();
				},
					success: function(response)
				{	
					jQuery("#formLoader").hide();
					jQuery("#successmsg").html(response);
					jQuery("#successmsg").show().delay(3000).fadeOut();
					jQuery("#faq-form")[0].reset();
					jQuery(".query-form").fadeOut(4000);
					jQuery(".query-form-parent").fadeOut(4000);
					
					
				}
			});
		}else{ return false; }
		});

	});
});
</script>
<script type="text/javascript">
require(['jquery'], function () {
	jQuery(document).ready(function(){
		jQuery(".cus-care-btn").click(function(){
			jQuery('.query-form-parent').fadeIn();
			jQuery('.query-form').fadeIn();
		});
		jQuery("#cancelpopup").click(function(){
			jQuery(".query-form").fadeOut();
			jQuery(".query-form-parent").fadeOut();
		});
	});
});
</script>

