
<?php  $block->zipcode();

  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
       $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');	 
	   $mediapath =  $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
	      $filepath =   $mediapath.'zipcode/loading.gif';
?>


<form action="" name="zipcodechker" method="post">
<div id="container">
	<div class="pincode-sec">
			<label class="pincode_lbl">Delivery</label>
             <input type="text" id="zipcode" name="zipcode" placeholder="Enter Pincode"/>
             <input type="button" id="button" class="pincode_btn" onclick="autoComplete()" value="CHECK" />  
	</div>			 
        </div>
		 <ul id="result"></ul>
		 

</form>

<!-- the result of the search will be rendered inside this div -->

        <script type="text/javascript">
		function autoComplete()
		{
			var searchVal = jQuery('#zipcode').val();
			var dataString = 'searchVal='+searchVal;
			if(searchVal!=""){
                    jQuery("#result").html("<img src='<?php echo $filepath ;?>'/>");
                       jQuery.ajax({
                            type:"post",
                            url:"<?php echo $block->getUrl('zipcode/index/zipcode');?>",
                            data:dataString,
                            success:function(data){
                               jQuery("#result").html(data);
                               
                             }
                          });
                      }else{
						  
						  alert("Please enter zipcode.");
					  }
			
		}
        </script>