<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<form class="form contact"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Contact Information') ?></span></legend><br />
        <div class="field note no-label"><?php /* @escapeNotVerified */ echo __('Lorem Ipsum is simply dummy text of the printing and typesetting.') ?></div>
        <div class="row">
            <div class="field name required col-sm-4">
                <?php /* <label class="label" for="name"><span><?php echo __('Name') ?></span></label> */ ?>
                <div class="control">
                    <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}" placeholder="Name" />
                </div>
            </div>
            <div class="field email required col-sm-4">
                <?php /* <label class="label" for="email"><span><?php echo __('Email') ?></span></label> */ ?>
                <div class="control">
                    <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}" placeholder="<?php /* @escapeNotVerified */ echo __('Email') ?>" />
                </div>
            </div>
            <div class="field telephone col-sm-4">
                <?php /* <label class="label" for="telephone"><span><?php echo __('Phone Number') ?></span></label> */ ?>
                <div class="control">
                    <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="" class="input-text" type="text" placeholder="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" />
                </div>
            </div>
        </div>
        <div class="field comment required">
            <?php /* <label class="label" for="comment"><span><?php  echo __('What’s on your mind?') ?></span></label> */ ?>
            <div class="control">
                <textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}" placeholder="<?php /* @escapeNotVerified */ echo __('Message') ?>"></textarea>
            </div>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
		
		
	
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('Send') ?></span>
            </button>
        </div>
    </div>
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contatctus_no')->toHtml();?> 
</form>
