<?php 


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
/** @var \Magento\Catalog\Model\ResourceModel\Product\Collection $productCollection */
$productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\Collection');
/** Apply filters here */
$productCollection->addAttributeToFilter('visibility', \Magento\Catalog\Model\Product\Visibility::VISIBILITY_BOTH)->addAttributeToFilter('status',\Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED)->addAttributeToSelect('*');

$productCollection->addFieldToFilter('our_faviourite','1');
$productCollection->load();

//echo "<pre>";print_r($productCollection ->getData()); 
foreach($productCollection as $_product){
	
	
	
	
}


?>