<?php

// @codingStandardsIgnoreFile
?>
<h1>CDN and Image Processing</h1>
<span>Serve your images at the fastest possible speed. We recommend the Sirv extension for Magento.</span> It will:<br/>
<br/>
<ul style="margin-left: 30px;">
    <li>Optimise your images smaller than any other Magento extension (with no quality loss).</li>
    <li>Serve your images faster than any other Magento extension (from a fast global CDN).</li>
    <li>Reduce the load on your Magento server.</li>
</ul>
Optimisation of such a high degree means your website can load up to 30% faster and images are up to 70% smaller. Furthermore, it typically improves Google search ranking and improves Google PageSpeed score by between 1% and 9%.<br/>
<br/>
Sirv is a free extension for Magento 1 and Magento 2. Designed to speed up websites, it offers business plans from $19/month for websites requiring more than the 2GB/month transfer allowance.<br/>
<br/>
<a href="https://sirv.com/download/magento/sirv-magento-2.zip" target="_blank" title="Sirv extension for Magento 2">Download the Sirv extension for Magento 2</a><br/>
<br/>
Sirv is a image optimisation, hosting and delivery service provided by our sister company. Please <a href="https://sirv.com/contact/" target="_blank" title="Email support">email us</a> any questions.
