<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
<?php
    $type = 'widget-product-grid';
    $mode = 'grid';
    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;  ?>
    <div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $mode; ?>">
        <?php if ($title):?>
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
        </div>
        <?php endif ?>
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */
            echo $mode; ?>">
                <ol class="newproduct product-items <?php /* @escapeNotVerified */ echo $type; ?>">
				
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item product">' : '</li><li class="product-item product">' ?>
                        <div class="product-item-info">
						<?php echo $block->getImage($_item, $image)->toHtml(); ?>
                          <?php /*  <a href="<?php   echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                
                            </a> */?>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>

                                <?php if ($templateType): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType, true) ?>
                                <?php endif; ?>

                                <?php echo $block->getProductPriceHtml($_item, $type); ?>

                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>


<script type="text/javascript">
    require(['jquery', 'OwlCarousel'], function () {
        jQuery(document).ready(function () {
            jQuery(".newproduct").owlCarousel({
				items: 4,
                itemsDesktop: [1367, 4],
                itemsDesktopSmall: [1024, 3],
                itemsTablet: [768, 2],
                itemsTabletSmall: [479, 1],
                pagination: false,  
                dots: true,		
                 loop:true,
				nav:true,
                navigation: true,
				
            });
        });
    });
</script>
